name: CI
on:
  pull_request:
    branches: [ develop, main, feature/** ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install core
        run: |
          pip install -e packages/newsroom_core
          pip install -e tools/newsroom-cli
          pip install jsonschema
      - name: Schema validation
        run: python packages/newsroom_core/newsroom_core/verify.py --validate-schemas
      - name: Bias lint
        run: python packages/newsroom_core/newsroom_core/bias_lint.py --repo .