name: Publish Website
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/main-website/package-lock.json
      - name: Install and build
        env:
          CONTENT_DIR: ${{ github.workspace }}/content/editorial-pipeline
        run: |
          cd apps/main-website
          npm ci
          npm run build
